#!/usr/bin/env python3
"""
compliance_extensions.py  —  Continuous compliance monitoring and trust reporting
for the pipeline_v3.py data pipeline suite.

Three classes that close the gap between point-in-time audit logging
(already handled by governance_extensions.py) and the continuous monitoring,
vendor risk management, and customer-facing trust reporting that enterprise
compliance programs like Vanta provide:

    ComplianceMonitor       Run hourly checks across all governance controls
                            and log CONTROL_OK / CONTROL_FAILED events to the
                            audit ledger.  Detects drift between runs.

    TrustReportGenerator    Compile a customer-facing security posture report
                            from all existing governance data — RoPA, audit
                            ledger stats, BAA registry, consent counts, PII
                            scan results, vendor risk, and active controls.

    VendorRiskTracker       Registry of third-party tools and services with
                            SOC 2 status, data types received, last review
                            date, and expiry alerting.

Revision history
────────────────
1.0   2026-03-23   Initial release: ComplianceMonitor, TrustReportGenerator,
                   VendorRiskTracker.
"""
from __future__ import annotations

import io
import json
import logging
import pathlib
import threading
from datetime import datetime, timedelta, timezone
from html import escape as _he
from typing import Dict, List, Optional, Union

logger = logging.getLogger(__name__)


# ── Module-level helpers ──────────────────────────────────────────────────────

def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _html_head(title: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_he(title)}</title>
<style>
  body{{font-family:'Segoe UI',Arial,sans-serif;margin:0;padding:24px;
       background:#f4f6f9;color:#1a1a2e;}}
  h1{{color:#1a1a2e;border-bottom:3px solid #4361ee;padding-bottom:8px;}}
  h2{{color:#4361ee;margin-top:32px;}}
  h3{{color:#3a0ca3;}}
  table{{width:100%;border-collapse:collapse;margin:12px 0;background:#fff;
         box-shadow:0 1px 4px rgba(0,0,0,.1);border-radius:6px;overflow:hidden;}}
  th{{background:#4361ee;color:#fff;padding:10px 14px;text-align:left;font-size:.85em;}}
  td{{padding:9px 14px;border-bottom:1px solid #e9ecef;font-size:.88em;
      vertical-align:top;}}
  tr:last-child td{{border-bottom:none;}}
  tr:hover td{{background:#f0f4ff;}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:12px;font-size:.78em;
           font-weight:600;}}
  .badge-green{{background:#d4edda;color:#155724;}}
  .badge-yellow{{background:#fff3cd;color:#856404;}}
  .badge-red{{background:#f8d7da;color:#721c24;}}
  .badge-blue{{background:#d1ecf1;color:#0c5460;}}
  .summary-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
                  gap:16px;margin:20px 0;}}
  .summary-card{{background:#fff;border-radius:8px;padding:18px;text-align:center;
                  box-shadow:0 1px 4px rgba(0,0,0,.08);}}
  .summary-card .num{{font-size:2em;font-weight:700;color:#4361ee;}}
  .summary-card .lbl{{font-size:.82em;color:#6c757d;margin-top:4px;}}
  .footer{{margin-top:40px;font-size:.78em;color:#6c757d;border-top:1px solid #dee2e6;
            padding-top:12px;}}
  .warn{{color:#856404;background:#fff3cd;padding:8px 12px;border-radius:4px;
          border-left:4px solid #ffc107;margin:8px 0;}}
  .ok{{color:#155724;background:#d4edda;padding:8px 12px;border-radius:4px;
        border-left:4px solid #28a745;margin:8px 0;}}
  .fail{{color:#721c24;background:#f8d7da;padding:8px 12px;border-radius:4px;
          border-left:4px solid #dc3545;margin:8px 0;}}
</style>
</head>
<body>
"""


def _html_foot() -> str:
    return f"""
<div class="footer">
  Generated by compliance_extensions.py &nbsp;|&nbsp;
  {_iso(_now_utc())} UTC &nbsp;|&nbsp;
  Confidential — for internal compliance use only
</div>
</body></html>"""


# ═════════════════════════════════════════════════════════════════════════════
#  1. ComplianceMonitor  —  continuous hourly controls monitoring
# ═════════════════════════════════════════════════════════════════════════════

class ComplianceMonitor:
    """
    Run automated checks across all governance controls and log the results
    to the audit ledger.  Designed to be called on a schedule (e.g. hourly)
    to provide continuous compliance visibility rather than point-in-time
    snapshots at pipeline run time.

    Each check returns CONTROL_OK or CONTROL_FAILED and is logged as a
    governance event so the tamper-evident audit chain captures every
    monitoring pass.

    Controls checked
    ────────────────
    AUDIT_LEDGER_INTACT         Ledger files exist and the hash chain is
                                unbroken (no tampering detected).
    ENCRYPTION_KEY_PRESENT      Encryption key version file exists and
                                contains at least one active key.
    CONSENT_DB_REACHABLE        The SQLite consent database file exists and
                                can be opened.
    BAA_REGISTRY_CURRENT        No BAA entries are expired; warn if any
                                expire within warn_days.
    IRB_REGISTRY_CURRENT        No IRB protocol entries are expired; warn
                                if any expire within warn_days.
    PURPOSE_REGISTRY_PRESENT    The purpose limitation registry file exists
                                and is non-empty.
    VENDOR_RISK_CURRENT         No vendor reviews are overdue; warn if any
                                are due within warn_days.
    LOG_DIR_WRITABLE            The governance log directory is writable —
                                a failed write would silently break auditing.

    Quick-start
    ───────────
        from compliance_extensions import ComplianceMonitor
        from pipeline_v3 import GovernanceLogger

        gov     = GovernanceLogger(run_id="monitor_001", src="scheduler")
        monitor = ComplianceMonitor(gov)

        results = monitor.run_all()
        monitor.save_report("compliance_status.html")

        # Run on a schedule
        import schedule, time
        schedule.every().hour.do(monitor.run_all)
        while True:
            schedule.run_pending()
            time.sleep(60)
    """

    # Control IDs — used as event action strings and report keys
    CTRL_LEDGER          = "AUDIT_LEDGER_INTACT"
    CTRL_ENCRYPTION      = "ENCRYPTION_KEY_PRESENT"
    CTRL_CONSENT         = "CONSENT_DB_REACHABLE"
    CTRL_BAA             = "BAA_REGISTRY_CURRENT"
    CTRL_IRB             = "IRB_REGISTRY_CURRENT"
    CTRL_PURPOSE         = "PURPOSE_REGISTRY_PRESENT"
    CTRL_VENDOR          = "VENDOR_RISK_CURRENT"
    CTRL_LOG_DIR         = "LOG_DIR_WRITABLE"

    def __init__(
        self,
        gov,
        warn_days:      int  = 30,
        dry_run:        bool = False,
    ) -> None:
        """
        Parameters
        ──────────
        gov         GovernanceLogger for audit events.
        warn_days   Controls that involve expiry dates will warn when
                    expiry is within this many days.
        dry_run     Run all checks and produce reports without writing
                    CONTROL_OK / CONTROL_FAILED events to the ledger.
        """
        self.gov       = gov
        self.warn_days = warn_days
        self.dry_run   = dry_run
        self._results: List[Dict] = []

    # ── Public API ────────────────────────────────────────────────────────────

    def run_all(self) -> List[Dict]:
        """
        Execute all controls checks and return a list of result dicts.
        Each result has keys: control_id, status, detail, checked_at.
        Status is one of: "OK", "WARN", "FAIL".
        """
        self._results = []
        checks = [
            (self.CTRL_LOG_DIR,     self._check_log_dir_writable),
            (self.CTRL_LEDGER,      self._check_audit_ledger),
            (self.CTRL_ENCRYPTION,  self._check_encryption_key),
            (self.CTRL_CONSENT,     self._check_consent_db),
            (self.CTRL_BAA,         self._check_baa_registry),
            (self.CTRL_IRB,         self._check_irb_registry),
            (self.CTRL_PURPOSE,     self._check_purpose_registry),
            (self.CTRL_VENDOR,      self._check_vendor_risk),
        ]
        for ctrl_id, check_fn in checks:
            try:
                status, detail = check_fn()
            except Exception as exc:  # pylint: disable=broad-exception-caught
                logger.warning("ComplianceMonitor: check %s raised: %s", ctrl_id, exc)
                status, detail = "FAIL", f"Check raised an exception: {exc}"

            result = {
                "control_id": ctrl_id,
                "status":     status,
                "detail":     detail,
                "checked_at": _iso(_now_utc()),
            }
            self._results.append(result)

            if not self.dry_run:
                level = "INFO" if status == "OK" else ("WARN" if status == "WARN" else "ERROR")
                self.gov._event(  # type: ignore[attr-defined]
                    "COMPLIANCE",
                    f"CONTROL_{'OK' if status == 'OK' else 'FAILED'}",
                    {"control_id": ctrl_id, "status": status, "detail": detail},
                    level=level,
                )

            icon = "✅" if status == "OK" else ("⚠️ " if status == "WARN" else "❌")
            print(f"  {icon}  [{ctrl_id}] {status} — {detail}")

        passed = sum(1 for r in self._results if r["status"] == "OK")
        warned = sum(1 for r in self._results if r["status"] == "WARN")
        failed = sum(1 for r in self._results if r["status"] == "FAIL")
        print(f"\n  Controls: {passed} OK  |  {warned} WARN  |  {failed} FAIL")
        return self._results

    def run_check(self, control_id: str) -> Dict:
        """Run a single named control check and return its result dict."""
        dispatch = {
            self.CTRL_LOG_DIR:    self._check_log_dir_writable,
            self.CTRL_LEDGER:     self._check_audit_ledger,
            self.CTRL_ENCRYPTION: self._check_encryption_key,
            self.CTRL_CONSENT:    self._check_consent_db,
            self.CTRL_BAA:        self._check_baa_registry,
            self.CTRL_IRB:        self._check_irb_registry,
            self.CTRL_PURPOSE:    self._check_purpose_registry,
            self.CTRL_VENDOR:     self._check_vendor_risk,
        }
        if control_id not in dispatch:
            raise ValueError(
                f"ComplianceMonitor: unknown control_id '{control_id}'. "
                f"Valid: {list(dispatch.keys())}"
            )
        status, detail = dispatch[control_id]()
        return {"control_id": control_id, "status": status,
                "detail": detail, "checked_at": _iso(_now_utc())}

    def save_report(
        self,
        path: Union[str, pathlib.Path],
        fmt:  str = "html",
    ) -> pathlib.Path:
        """Write the last run_all() results as HTML (default) or JSON."""
        if not self._results:
            raise RuntimeError(
                "ComplianceMonitor: call run_all() before save_report()."
            )
        path = pathlib.Path(path)
        if fmt == "json":
            path.write_text(
                json.dumps(self._results, indent=2), encoding="utf-8"
            )
        else:
            path.write_text(self._build_html(), encoding="utf-8")
        logger.info("ComplianceMonitor: report written → %s", path)
        return path

    # ── Individual control checks ─────────────────────────────────────────────

    def _check_log_dir_writable(self) -> tuple:
        """Verify the governance log directory is writable."""
        log_dir = pathlib.Path(self.gov.log_dir)  # type: ignore[attr-defined]
        if not log_dir.exists():
            return "FAIL", f"Log directory does not exist: {log_dir}"
        probe = log_dir / ".write_probe"
        try:
            probe.write_text("probe", encoding="utf-8")
            probe.unlink()
            return "OK", f"Log directory writable: {log_dir}"
        except OSError as exc:
            return "FAIL", f"Log directory not writable: {exc}"

    def _check_audit_ledger(self) -> tuple:
        """Verify at least one audit ledger file exists and is non-empty."""
        log_dir = pathlib.Path(self.gov.log_dir)  # type: ignore[attr-defined]
        ledger_files = sorted(log_dir.glob("audit_ledger*.jsonl"))
        if not ledger_files:
            return "WARN", "No audit ledger files found — pipeline may not have run yet."
        total_events = 0
        for f in ledger_files:
            lines = [l for l in f.read_text(encoding="utf-8").splitlines() if l.strip()]
            total_events += len(lines)
        if total_events == 0:
            return "WARN", "Ledger files exist but contain no events."
        return "OK", f"{len(ledger_files)} ledger file(s), {total_events} event(s) total."

    def _check_encryption_key(self) -> tuple:
        """Verify the encryption key version file exists and has active keys."""
        key_file = pathlib.Path(self.gov.log_dir) / "encryption_key_versions.json"  # type: ignore[attr-defined]
        if not key_file.exists():
            return "WARN", "Encryption key version file not found — ColumnEncryptor not yet used."
        try:
            data = json.loads(key_file.read_text(encoding="utf-8"))
            if not data:
                return "WARN", "Encryption key file is empty — no keys registered."
            return "OK", f"{len(data)} encryption key version(s) registered."
        except Exception as exc:  # pylint: disable=broad-exception-caught
            return "FAIL", f"Could not read encryption key file: {exc}"

    def _check_consent_db(self) -> tuple:
        """Verify the consent SQLite database exists and is openable."""
        consent_db = pathlib.Path(self.gov.log_dir) / "consent.db"  # type: ignore[attr-defined]
        if not consent_db.exists():
            return "WARN", "Consent database not found — ConsentManager not yet used."
        try:
            import sqlite3
            conn = sqlite3.connect(str(consent_db), timeout=5)
            conn.execute("SELECT COUNT(*) FROM consent_records")
            count = conn.execute(
                "SELECT COUNT(*) FROM consent_records"
            ).fetchone()[0]
            conn.close()
            return "OK", f"Consent database reachable — {count} consent record(s)."
        except Exception as exc:  # pylint: disable=broad-exception-caught
            return "FAIL", f"Consent database check failed: {exc}"

    def _check_baa_registry(self) -> tuple:
        """Check BAA registry for expired or near-expiry entries."""
        baa_file = pathlib.Path(self.gov.log_dir) / "baa_registry.json"  # type: ignore[attr-defined]
        if not baa_file.exists():
            return "WARN", "BAA registry not found — BAATracker not yet used."
        try:
            registry = json.loads(baa_file.read_text(encoding="utf-8"))
        except Exception as exc:  # pylint: disable=broad-exception-caught
            return "FAIL", f"Could not read BAA registry: {exc}"
        if not registry:
            return "WARN", "BAA registry is empty — no BAAs registered."

        today   = _now_utc().date()
        expired, expiring = [], []
        for dest_id, rec in registry.items():
            expiry = datetime.fromisoformat(rec["expiry_date"]).date()
            days   = (expiry - today).days
            if days < 0:
                expired.append(dest_id)
            elif days <= self.warn_days:
                expiring.append(f"{dest_id} ({days}d)")

        if expired:
            return "FAIL", f"{len(expired)} expired BAA(s): {expired}"
        if expiring:
            return "WARN", f"BAA(s) expiring soon: {expiring}"
        return "OK", f"{len(registry)} active BAA(s), none expiring within {self.warn_days} days."

    def _check_irb_registry(self) -> tuple:
        """Check IRB registry for expired or near-expiry protocols."""
        irb_file = pathlib.Path(self.gov.log_dir) / "irb_registry.json"  # type: ignore[attr-defined]
        if not irb_file.exists():
            return "WARN", "IRB registry not found — IRBApprovalGate not yet used."
        try:
            registry = json.loads(irb_file.read_text(encoding="utf-8"))
        except Exception as exc:  # pylint: disable=broad-exception-caught
            return "FAIL", f"Could not read IRB registry: {exc}"
        if not registry:
            return "WARN", "IRB registry is empty."

        today    = _now_utc().date()
        expired, expiring = [], []
        for pid, rec in registry.items():
            expiry = datetime.fromisoformat(rec["expiry_date"]).date()
            days   = (expiry - today).days
            if days < 0:
                expired.append(pid)
            elif days <= self.warn_days:
                expiring.append(f"{pid} ({days}d)")

        if expired:
            return "FAIL", f"{len(expired)} expired IRB protocol(s): {expired}"
        if expiring:
            return "WARN", f"Protocol(s) expiring soon: {expiring}"
        return "OK", f"{len(registry)} active protocol(s), none expiring within {self.warn_days} days."

    def _check_purpose_registry(self) -> tuple:
        """Verify the purpose limitation registry file exists and is populated."""
        purpose_file = pathlib.Path(self.gov.log_dir) / "purpose_registry.json"  # type: ignore[attr-defined]
        if not purpose_file.exists():
            return "WARN", "Purpose registry not found — PurposeLimitationEnforcer not yet used."
        try:
            data = json.loads(purpose_file.read_text(encoding="utf-8"))
            if not data:
                return "WARN", "Purpose registry exists but is empty."
            return "OK", f"{len(data)} purpose mapping(s) registered."
        except Exception as exc:  # pylint: disable=broad-exception-caught
            return "FAIL", f"Could not read purpose registry: {exc}"

    def _check_vendor_risk(self) -> tuple:
        """Check vendor risk registry for overdue reviews."""
        vendor_file = pathlib.Path(self.gov.log_dir) / "vendor_registry.json"  # type: ignore[attr-defined]
        if not vendor_file.exists():
            return "WARN", "Vendor registry not found — VendorRiskTracker not yet used."
        try:
            registry = json.loads(vendor_file.read_text(encoding="utf-8"))
        except Exception as exc:  # pylint: disable=broad-exception-caught
            return "FAIL", f"Could not read vendor registry: {exc}"
        if not registry:
            return "WARN", "Vendor registry is empty."

        today    = _now_utc().date()
        overdue, due_soon = [], []
        for vid, rec in registry.items():
            raw_date = rec.get("next_review_date", "")
            if not raw_date:
                due_soon.append(f"{vid} (no review date set)")
                continue
            try:
                next_review = datetime.fromisoformat(raw_date).date()
            except (ValueError, TypeError):
                due_soon.append(f"{vid} (invalid date: {raw_date!r})")
                continue
            days = (next_review - today).days
            if days < 0:
                overdue.append(vid)
            elif days <= self.warn_days:
                due_soon.append(f"{vid} ({days}d)")

        if overdue:
            return "FAIL", f"{len(overdue)} overdue vendor review(s): {overdue}"
        if due_soon:
            return "WARN", f"Vendor review(s) due soon: {due_soon}"
        return "OK", f"{len(registry)} vendor(s), all reviews current."

    # ── HTML report ───────────────────────────────────────────────────────────

    def _build_html(self) -> str:
        passed = sum(1 for r in self._results if r["status"] == "OK")
        warned = sum(1 for r in self._results if r["status"] == "WARN")
        failed = sum(1 for r in self._results if r["status"] == "FAIL")
        total  = len(self._results)

        overall_badge = "badge-green" if failed == 0 and warned == 0 \
            else ("badge-yellow" if failed == 0 else "badge-red")
        overall_label = "ALL CONTROLS PASSING" if failed == 0 and warned == 0 \
            else (f"{warned} WARNING(S)" if failed == 0 else f"{failed} CONTROL(S) FAILED")

        buf = io.StringIO()
        buf.write(_html_head("Compliance Controls Status"))
        buf.write("<h1>🔒 Compliance Controls Status</h1>\n")
        buf.write(
            f"<div class='summary-grid'>"
            f"<div class='summary-card'><div class='num'>{total}</div>"
            f"<div class='lbl'>Total Controls</div></div>"
            f"<div class='summary-card'><div class='num' style='color:#28a745'>{passed}</div>"
            f"<div class='lbl'>Passing</div></div>"
            f"<div class='summary-card'><div class='num' style='color:#ffc107'>{warned}</div>"
            f"<div class='lbl'>Warnings</div></div>"
            f"<div class='summary-card'><div class='num' style='color:#dc3545'>{failed}</div>"
            f"<div class='lbl'>Failed</div></div>"
            f"</div>\n"
            f"<p><span class='badge {overall_badge}'>{_he(overall_label)}</span></p>\n"
        )

        buf.write(
            "<h2>Control Results</h2>"
            "<table><tr><th>Control</th><th>Status</th><th>Detail</th>"
            "<th>Checked At</th></tr>\n"
        )
        for r in self._results:
            badge = {"OK": "badge-green", "WARN": "badge-yellow",
                     "FAIL": "badge-red"}.get(r["status"], "badge-blue")
            buf.write(
                f"<tr>"
                f"<td><code>{_he(r['control_id'])}</code></td>"
                f"<td><span class='badge {badge}'>{_he(r['status'])}</span></td>"
                f"<td>{_he(r['detail'])}</td>"
                f"<td>{_he(r['checked_at'][:19])}</td>"
                f"</tr>\n"
            )
        buf.write("</table>\n")
        buf.write(_html_foot())
        return buf.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
#  2. VendorRiskTracker  —  third-party vendor security registry
# ═════════════════════════════════════════════════════════════════════════════

class VendorRiskTracker:
    """
    Maintain a registry of third-party vendors and services that receive or
    process data from the pipeline, tracking their security posture, SOC 2
    status, last review date, and the types of data they handle.

    This addresses the vendor risk management gap identified in SOC 2 and
    GDPR Art. 28 (processor agreements).  Every destination loader in
    pipeline_v3.py represents a vendor that should appear in this registry.

    Registry format (vendor_registry.json)
    ───────────────────────────────────────
    Each entry is keyed by vendor_id and contains:
        vendor_name         Human-readable name (e.g. "Snowflake Inc.")
        service_type        What the vendor provides (e.g. "cloud data warehouse")
        data_types          List of data categories sent to this vendor
        soc2_status         "certified" | "in_progress" | "not_certified" | "unknown"
        soc2_report_date    Date of most recent SOC 2 report (ISO string)
        last_review_date    Date of most recent internal vendor review
        next_review_date    Date the next review is due
        dpa_signed          Whether a Data Processing Agreement is signed (bool)
        dpa_date            Date DPA was signed
        risk_level          "low" | "medium" | "high" | "critical"
        notes               Free text notes

    Quick-start
    ───────────
        from compliance_extensions import VendorRiskTracker
        from pipeline_v3 import GovernanceLogger

        gov     = GovernanceLogger(run_id="run_001", src="compliance")
        tracker = VendorRiskTracker(gov)

        tracker.register_vendor(
            vendor_id        = "snowflake_prod",
            vendor_name      = "Snowflake Inc.",
            service_type     = "cloud data warehouse",
            data_types       = ["employee_data", "financial_data"],
            soc2_status      = "certified",
            soc2_report_date = "2024-11-01",
            last_review_date = "2025-01-15",
            next_review_date = "2026-01-15",
            dpa_signed       = True,
            dpa_date         = "2024-01-01",
            risk_level       = "medium",
        )

        tracker.check_vendor("snowflake_prod")
        tracker.export_register("vendor_register.html")
    """

    _REGISTRY_FILE = "vendor_registry.json"
    _VALID_SOC2    = {"certified", "in_progress", "not_certified", "unknown"}
    _VALID_RISK    = {"low", "medium", "high", "critical"}

    def __init__(
        self,
        gov,
        warn_days: int  = 30,
        dry_run:   bool = False,
    ) -> None:
        self.gov       = gov
        self.warn_days = warn_days
        self.dry_run   = dry_run
        self._lock     = threading.Lock()
        self._path     = pathlib.Path(gov.log_dir) / self._REGISTRY_FILE  # type: ignore[attr-defined]
        self._registry: Dict[str, Dict] = self._load()

    # ── Public API ────────────────────────────────────────────────────────────

    def register_vendor(
        self,
        vendor_id:        str,
        vendor_name:      str,
        service_type:     str,
        data_types:       Optional[List[str]] = None,
        soc2_status:      str  = "unknown",
        soc2_report_date: Optional[str] = None,
        last_review_date: Optional[str] = None,
        next_review_date: Optional[str] = None,
        dpa_signed:       bool = False,
        dpa_date:         Optional[str] = None,
        risk_level:       str  = "medium",
        notes:            str  = "",
    ) -> None:
        """Add or update a vendor in the registry."""
        if soc2_status not in self._VALID_SOC2:
            raise ValueError(
                f"VendorRiskTracker: soc2_status must be one of "
                f"{self._VALID_SOC2}, got '{soc2_status}'."
            )
        if risk_level not in self._VALID_RISK:
            raise ValueError(
                f"VendorRiskTracker: risk_level must be one of "
                f"{self._VALID_RISK}, got '{risk_level}'."
            )

        # Default next_review_date to 1 year from today if not provided
        if not next_review_date:
            next_review_date = (
                _now_utc().date() + timedelta(days=365)
            ).isoformat()

        record = {
            "vendor_id":        vendor_id,
            "vendor_name":      vendor_name,
            "service_type":     service_type,
            "data_types":       data_types or [],
            "soc2_status":      soc2_status,
            "soc2_report_date": soc2_report_date or "",
            "last_review_date": last_review_date or _now_utc().date().isoformat(),
            "next_review_date": next_review_date,
            "dpa_signed":       dpa_signed,
            "dpa_date":         dpa_date or "",
            "risk_level":       risk_level,
            "notes":            notes,
            "registered_at":    _now_utc().isoformat(),
        }
        with self._lock:
            self._registry[vendor_id] = record
            self._save()

        self.gov._event(  # type: ignore[attr-defined]
            "COMPLIANCE", "VENDOR_REGISTERED",
            {"vendor_id":   vendor_id,
             "vendor_name": vendor_name,
             "risk_level":  risk_level,
             "soc2_status": soc2_status,
             "dpa_signed":  dpa_signed},
        )
        print(f"  ✅  Vendor registered: {vendor_id} ({vendor_name}) "
              f"— risk: {risk_level}, SOC 2: {soc2_status}")

    def check_vendor(self, vendor_id: str) -> Dict:
        """
        Return the vendor record and log a VENDOR_REVIEW_CHECKED event.
        Warns if the vendor review is overdue or DPA is missing.
        Raises ValueError if vendor_id is not in the registry.
        """
        record = self._registry.get(vendor_id)
        if not record:
            raise ValueError(
                f"VendorRiskTracker: vendor '{vendor_id}' not in registry. "
                f"Register with tracker.register_vendor(...)."
            )

        today       = _now_utc().date()
        next_review = datetime.fromisoformat(record["next_review_date"]).date()
        days_until  = (next_review - today).days

        if days_until < 0:
            logger.warning(
                "VendorRiskTracker: review overdue for %s by %d day(s)",
                vendor_id, abs(days_until)
            )
        elif days_until <= self.warn_days:
            logger.warning(
                "VendorRiskTracker: review for %s due in %d day(s)",
                vendor_id, days_until
            )

        if not record.get("dpa_signed"):
            logger.warning(
                "VendorRiskTracker: no DPA signed for %s — "
                "required for GDPR Art. 28 compliance.", vendor_id
            )

        self.gov._event(  # type: ignore[attr-defined]
            "COMPLIANCE", "VENDOR_REVIEW_CHECKED",
            {"vendor_id":      vendor_id,
             "vendor_name":    record["vendor_name"],
             "risk_level":     record["risk_level"],
             "soc2_status":    record["soc2_status"],
             "dpa_signed":     record["dpa_signed"],
             "next_review":    record["next_review_date"],
             "days_until_review": days_until},
        )
        return record

    def get_overdue_reviews(self) -> List[Dict]:
        """Return all vendors whose review date has passed."""
        today = _now_utc().date()
        return [
            {**rec, "days_overdue": (today - datetime.fromisoformat(
                rec["next_review_date"]).date()).days}
            for rec in self._registry.values()
            if datetime.fromisoformat(rec["next_review_date"]).date() < today
        ]

    def get_high_risk_vendors(self) -> List[Dict]:
        """Return all vendors with risk_level 'high' or 'critical'."""
        return [
            rec for rec in self._registry.values()
            if rec["risk_level"] in ("high", "critical")
        ]

    def get_missing_dpa(self) -> List[Dict]:
        """Return all vendors without a signed DPA."""
        return [
            rec for rec in self._registry.values()
            if not rec.get("dpa_signed")
        ]

    def all_vendors(self) -> List[Dict]:
        return list(self._registry.values())

    def export_register(self, path: Union[str, pathlib.Path]) -> pathlib.Path:
        """Write an HTML vendor risk register."""
        path = pathlib.Path(path)
        path.write_text(self._build_html(), encoding="utf-8")
        logger.info("VendorRiskTracker: register exported → %s", path)
        return path

    # ── Internals ─────────────────────────────────────────────────────────────

    def _load(self) -> Dict:
        if self._path.exists():
            try:
                return json.loads(self._path.read_text(encoding="utf-8"))
            except Exception as exc:  # pylint: disable=broad-exception-caught
                logger.warning(
                    "VendorRiskTracker: could not load registry from %s: %s "
                    "— starting with empty registry.", self._path, exc
                )
        return {}

    def _save(self) -> None:
        self._path.write_text(
            json.dumps(self._registry, indent=2), encoding="utf-8"
        )

    def _build_html(self) -> str:
        today    = _now_utc().date()
        buf      = io.StringIO()
        overdue  = self.get_overdue_reviews()
        no_dpa   = self.get_missing_dpa()
        high_risk = self.get_high_risk_vendors()

        buf.write(_html_head("Vendor Risk Register"))
        buf.write("<h1>🏢 Vendor Risk Register</h1>\n")
        buf.write(
            f"<div class='summary-grid'>"
            f"<div class='summary-card'><div class='num'>{len(self._registry)}</div>"
            f"<div class='lbl'>Total Vendors</div></div>"
            f"<div class='summary-card'><div class='num' style='color:#dc3545'>"
            f"{len(overdue)}</div>"
            f"<div class='lbl'>Overdue Reviews</div></div>"
            f"<div class='summary-card'><div class='num' style='color:#ffc107'>"
            f"{len(no_dpa)}</div>"
            f"<div class='lbl'>Missing DPA</div></div>"
            f"<div class='summary-card'><div class='num' style='color:#dc3545'>"
            f"{len(high_risk)}</div>"
            f"<div class='lbl'>High / Critical Risk</div></div>"
            f"</div>\n"
        )

        if self._registry:
            _soc2_badge = {
                "certified":     "badge-green",
                "in_progress":   "badge-yellow",
                "not_certified": "badge-red",
                "unknown":       "badge-blue",
            }
            _risk_badge = {
                "low":      "badge-green",
                "medium":   "badge-yellow",
                "high":     "badge-red",
                "critical": "badge-red",
            }
            buf.write(
                "<h2>All Vendors</h2>"
                "<table><tr><th>Vendor</th><th>Service</th><th>Risk</th>"
                "<th>SOC 2</th><th>DPA</th><th>Next Review</th>"
                "<th>Data Types</th></tr>\n"
            )
            for rec in sorted(self._registry.values(),
                              key=lambda r: r["risk_level"],
                              reverse=True):
                next_rev  = datetime.fromisoformat(rec["next_review_date"]).date()
                days_left = (next_rev - today).days
                rev_label = (
                    f"<span class='badge badge-red'>OVERDUE {abs(days_left)}d</span>"
                    if days_left < 0 else
                    f"<span class='badge badge-yellow'>{days_left}d</span>"
                    if days_left <= self.warn_days else
                    f"{_he(rec['next_review_date'])}"
                )
                dpa_badge = (
                    "<span class='badge badge-green'>Signed</span>"
                    if rec["dpa_signed"] else
                    "<span class='badge badge-red'>Missing</span>"
                )
                data_str = _he(", ".join(rec.get("data_types", [])) or "—")
                buf.write(
                    f"<tr>"
                    f"<td><strong>{_he(rec['vendor_name'])}</strong><br>"
                    f"<small>{_he(rec['vendor_id'])}</small></td>"
                    f"<td>{_he(rec['service_type'])}</td>"
                    "<td><span class='badge " + _risk_badge.get(rec['risk_level'], 'badge-blue') + "'>"
                    f"{_he(rec['risk_level'].upper())}</span></td>"
                    "<td><span class='badge " + _soc2_badge.get(rec['soc2_status'], 'badge-blue') + "'>"
                    f"{_he(rec['soc2_status'])}</span></td>"
                    f"<td>{dpa_badge}</td>"
                    f"<td>{rev_label}</td>"
                    f"<td>{data_str}</td>"
                    f"</tr>\n"
                )
            buf.write("</table>\n")
        else:
            buf.write("<p>No vendors registered.</p>\n")

        buf.write(_html_foot())
        return buf.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
#  3. TrustReportGenerator  —  customer-facing security posture report
# ═════════════════════════════════════════════════════════════════════════════

class TrustReportGenerator:
    """
    Compile a customer-facing security posture report from all existing
    governance data in the pipeline's log directory.

    This is the "Trust Center" equivalent — a single HTML document you can
    share with enterprise customers, auditors, or prospects to demonstrate
    your security and compliance posture without giving them access to your
    internal systems.

    Data sources compiled into the report
    ──────────────────────────────────────
    Audit ledger        Total events, date range, categories breakdown
    BAA registry        Number of active BAAs, next expiry
    IRB registry        Active protocols (count only, titles redacted by default)
    Consent database    Total consent records, purposes covered
    Vendor registry     Vendor count, SOC 2 coverage, DPA coverage
    Compliance monitor  Last controls check results (if available)
    Pipeline metadata   Frameworks covered (GDPR, CCPA, HIPAA, OMOP)
    Purpose registry    Registered data processing purposes

    Privacy note: the report shows counts and statuses — not raw personal
    data, not individual consent records, not specific IRB study titles
    (unless show_irb_titles=True).

    Quick-start
    ───────────
        from compliance_extensions import TrustReportGenerator
        from pipeline_v3 import GovernanceLogger

        gov      = GovernanceLogger(run_id="trust_001", src="compliance")
        reporter = TrustReportGenerator(gov, org_name="Acme Analytics")

        reporter.generate("trust_report.html")
    """

    _FRAMEWORKS = [
        ("GDPR",        "EU General Data Protection Regulation",
         "Art. 5, 13, 15, 17, 25, 30, 32, 33"),
        ("CCPA",        "California Consumer Privacy Act",
         "§1798.100 – §1798.199"),
        ("HIPAA",       "Health Insurance Portability and Accountability Act",
         "Safe Harbor §164.514(b), BAA §164.308(b)(1)"),
        ("OMOP CDM",    "Observational Medical Outcomes Partnership",
         "CDM v5.4 domain mappings"),
        ("SOC 2",       "Service Organization Control 2",
         "Security, Availability, Processing Integrity, Confidentiality, Privacy"),
    ]

    _SECURITY_CONTROLS = [
        ("AES-256 Column Encryption",       "Data encrypted at rest using AES-256 via Fernet"),
        ("Tamper-Evident Audit Ledger",     "SHA-256 hash chain — any modification is detectable"),
        ("PII Detection & Masking",         "Automatic detection and masking of 20+ PII field types"),
        ("Pseudonymization Vault",          "Fernet encryption with context separation and key rotation"),
        ("Differential Privacy",            "Laplace/Gaussian noise with per-column privacy budgets"),
        ("Consent Management",              "Per-subject, per-purpose consent with expiry and withdrawal"),
        ("Purpose Limitation Enforcement",  "Columns not approved for declared purpose are dropped"),
        ("GDPR Art. 17 Erasure",            "Right to erasure enforced across all 18 destinations"),
        ("BAA Gating",                      "PHI loads blocked without a current signed BAA"),
        ("IRB Protocol Enforcement",        "Column-level gating against approved research data elements"),
        ("HIPAA Safe Harbor",               "All 18 identifier categories detected and removed/masked"),
        ("k-Anonymity Enforcement",         "Quasi-identifier groups below k=5 suppressed before release"),
        ("Schema Validation",               "Schema drift detection and data contract enforcement"),
        ("Secrets Management",              "Credentials loaded from environment — never hardcoded"),
        ("Cross-Border Transfer Logging",   "All international data transfers logged with legal basis"),
    ]

    def __init__(
        self,
        gov,
        org_name:          str  = "Your Organization",
        show_irb_titles:   bool = False,
        include_vendors:   bool = True,
        dry_run:           bool = False,
    ) -> None:
        """
        Parameters
        ──────────
        gov                 GovernanceLogger for audit events.
        org_name            Your organization name — shown in the report header.
        show_irb_titles     If True, IRB study titles are included in the report.
                            Default False — counts only, no study details.
        include_vendors     If True, include vendor risk summary section.
        dry_run             Generate report without logging a TRUST_REPORT_GENERATED
                            event to the audit ledger.
        """
        self.gov              = gov
        self.org_name         = org_name
        self.show_irb_titles  = show_irb_titles
        self.include_vendors  = include_vendors
        self.dry_run          = dry_run
        self._log_dir         = pathlib.Path(gov.log_dir)  # type: ignore[attr-defined]

    # ── Public API ────────────────────────────────────────────────────────────

    def generate(self, path: Union[str, pathlib.Path]) -> pathlib.Path:
        """
        Compile and write the trust report to disk.
        Logs TRUST_REPORT_GENERATED to the governance ledger.
        Returns the path of the written file.
        """
        path = pathlib.Path(path)
        data = self._collect_data()
        path.write_text(self._build_html(data), encoding="utf-8")

        if not self.dry_run:
            self.gov._event(  # type: ignore[attr-defined]
                "COMPLIANCE", "TRUST_REPORT_GENERATED",
                {"path":        str(path),
                 "org_name":    self.org_name,
                 "audit_events": data["ledger"]["total_events"],
                 "baa_count":   data["baa"]["count"],
                 "vendor_count": data["vendors"]["count"]},
            )
        logger.info("TrustReportGenerator: trust report written → %s", path)
        print(f"  ✅  Trust report generated → {path}")
        return path

    # ── Data collection ───────────────────────────────────────────────────────

    def _collect_data(self) -> Dict:
        return {
            "generated_at": _iso(_now_utc()),
            "org_name":     self.org_name,
            "ledger":       self._collect_ledger(),
            "baa":          self._collect_baa(),
            "irb":          self._collect_irb(),
            "consent":      self._collect_consent(),
            "vendors":      self._collect_vendors(),
            "purpose":      self._collect_purpose(),
            "controls":     self._collect_controls(),
        }

    def _collect_ledger(self) -> Dict:
        ledger_files = sorted(self._log_dir.glob("audit_ledger*.jsonl"))
        if not ledger_files:
            return {"total_events": 0, "date_range": "No events yet",
                    "categories": {}}
        events = []
        for f in ledger_files:
            for line in f.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line:
                    try:
                        events.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass

        categories: Dict[str, int] = {}
        for ev in events:
            cat = ev.get("category", "UNKNOWN")
            categories[cat] = categories.get(cat, 0) + 1

        timestamps = [ev.get("timestamp_utc", "") for ev in events if ev.get("timestamp_utc")]
        date_range = (
            f"{min(timestamps)[:10]} — {max(timestamps)[:10]}"
            if timestamps else "Unknown"
        )
        return {
            "total_events": len(events),
            "date_range":   date_range,
            "categories":   categories,
        }

    def _collect_baa(self) -> Dict:
        baa_file = self._log_dir / "baa_registry.json"
        if not baa_file.exists():
            return {"count": 0, "active": 0, "next_expiry": "N/A"}
        try:
            registry = json.loads(baa_file.read_text(encoding="utf-8"))
        except Exception:  # pylint: disable=broad-exception-caught
            return {"count": 0, "active": 0, "next_expiry": "N/A"}

        today  = _now_utc().date()
        active = [
            rec for rec in registry.values()
            if datetime.fromisoformat(rec["expiry_date"]).date() >= today
        ]
        expiries = sorted(
            datetime.fromisoformat(r["expiry_date"]).date()
            for r in active
        )
        return {
            "count":       len(registry),
            "active":      len(active),
            "next_expiry": str(expiries[0]) if expiries else "N/A",
        }

    def _collect_irb(self) -> Dict:
        irb_file = self._log_dir / "irb_registry.json"
        if not irb_file.exists():
            return {"count": 0, "active": 0, "titles": []}
        try:
            registry = json.loads(irb_file.read_text(encoding="utf-8"))
        except Exception:  # pylint: disable=broad-exception-caught
            return {"count": 0, "active": 0, "titles": []}

        today  = _now_utc().date()
        active = [
            rec for rec in registry.values()
            if datetime.fromisoformat(rec["expiry_date"]).date() >= today
        ]
        titles = [rec["study_title"] for rec in active] if self.show_irb_titles else []
        return {"count": len(registry), "active": len(active), "titles": titles}

    def _collect_consent(self) -> Dict:
        db_file = self._log_dir / "consent.db"
        if not db_file.exists():
            return {"total_records": 0, "purposes": []}
        try:
            import sqlite3
            conn     = sqlite3.connect(str(db_file), timeout=5)
            total    = conn.execute(
                "SELECT COUNT(*) FROM consent_records"
            ).fetchone()[0]
            purposes = [
                row[0] for row in conn.execute(
                    "SELECT DISTINCT purpose FROM consent_records"
                ).fetchall()
            ]
            conn.close()
            return {"total_records": total, "purposes": purposes}
        except Exception:  # pylint: disable=broad-exception-caught
            return {"total_records": 0, "purposes": []}

    def _collect_vendors(self) -> Dict:
        vendor_file = self._log_dir / "vendor_registry.json"
        if not vendor_file.exists():
            return {"count": 0, "soc2_certified": 0, "dpa_signed": 0}
        try:
            registry = json.loads(vendor_file.read_text(encoding="utf-8"))
        except Exception:  # pylint: disable=broad-exception-caught
            return {"count": 0, "soc2_certified": 0, "dpa_signed": 0}

        soc2_cert = sum(
            1 for r in registry.values() if r.get("soc2_status") == "certified"
        )
        dpa_signed = sum(
            1 for r in registry.values() if r.get("dpa_signed")
        )
        return {
            "count":         len(registry),
            "soc2_certified": soc2_cert,
            "dpa_signed":    dpa_signed,
        }

    def _collect_purpose(self) -> Dict:
        purpose_file = self._log_dir / "purpose_registry.json"
        if not purpose_file.exists():
            return {"count": 0, "purposes": []}
        try:
            data = json.loads(purpose_file.read_text(encoding="utf-8"))
            return {"count": len(data), "purposes": list(data.keys())}
        except Exception:  # pylint: disable=broad-exception-caught
            return {"count": 0, "purposes": []}

    def _collect_controls(self) -> Dict:
        """Read the most recent compliance monitor results if available."""
        results_files = sorted(
            self._log_dir.glob("compliance_status*.json"),
            reverse=True,
        )
        if not results_files:
            return {"available": False, "results": []}
        try:
            results = json.loads(results_files[0].read_text(encoding="utf-8"))
            return {"available": True, "results": results,
                    "file": results_files[0].name}
        except Exception:  # pylint: disable=broad-exception-caught
            return {"available": False, "results": []}

    # ── HTML report ───────────────────────────────────────────────────────────

    def _build_html(self, d: Dict) -> str:
        buf = io.StringIO()
        buf.write(_html_head(f"Security & Compliance — {_he(d['org_name'])}"))
        buf.write(
            f"<h1>🛡️ Security &amp; Compliance Posture</h1>\n"
            f"<p><strong>{_he(d['org_name'])}</strong> &nbsp;·&nbsp; "
            f"Report generated: {_he(d['generated_at'][:19])} UTC</p>\n"
        )

        # ── Summary metrics ────────────────────────────────────────────────
        buf.write(
            f"<div class='summary-grid'>"
            f"<div class='summary-card'>"
            f"<div class='num'>{d['ledger']['total_events']:,}</div>"
            f"<div class='lbl'>Audit Events Logged</div></div>"
            f"<div class='summary-card'>"
            f"<div class='num'>{d['baa']['active']}</div>"
            f"<div class='lbl'>Active BAAs</div></div>"
            f"<div class='summary-card'>"
            f"<div class='num'>{d['consent']['total_records']:,}</div>"
            f"<div class='lbl'>Consent Records</div></div>"
            f"<div class='summary-card'>"
            f"<div class='num'>{d['vendors']['count']}</div>"
            f"<div class='lbl'>Vendors Reviewed</div></div>"
            f"</div>\n"
        )

        # ── Compliance frameworks ──────────────────────────────────────────
        buf.write("<h2>Compliance Frameworks</h2>\n<table>"
                  "<tr><th>Framework</th><th>Full Name</th>"
                  "<th>Coverage</th></tr>\n")
        for name, full, coverage in self._FRAMEWORKS:
            buf.write(
                f"<tr><td><strong>{_he(name)}</strong></td>"
                f"<td>{_he(full)}</td>"
                f"<td><span class='badge badge-green'>✓ Covered</span> "
                f"{_he(coverage)}</td></tr>\n"
            )
        buf.write("</table>\n")

        # ── Security controls ──────────────────────────────────────────────
        buf.write("<h2>Security Controls</h2>\n<table>"
                  "<tr><th>Control</th><th>Description</th><th>Status</th></tr>\n")
        for ctrl, desc in self._SECURITY_CONTROLS:
            buf.write(
                f"<tr><td><strong>{_he(ctrl)}</strong></td>"
                f"<td>{_he(desc)}</td>"
                f"<td><span class='badge badge-green'>✓ Implemented</span></td></tr>\n"
            )
        buf.write("</table>\n")

        # ── Audit ledger summary ───────────────────────────────────────────
        buf.write(
            f"<h2>Audit Logging</h2>\n"
            f"<p>All pipeline operations are recorded in a tamper-evident "
            f"SHA-256 hash chain audit ledger.</p>\n"
            f"<table><tr><th>Metric</th><th>Value</th></tr>\n"
            f"<tr><td>Total events logged</td>"
            f"<td>{d['ledger']['total_events']:,}</td></tr>\n"
            f"<tr><td>Date range</td>"
            f"<td>{_he(d['ledger']['date_range'])}</td></tr>\n"
        )
        for cat, count in sorted(d["ledger"]["categories"].items()):
            buf.write(
                f"<tr><td>— {_he(cat)} events</td><td>{count:,}</td></tr>\n"
            )
        buf.write("</table>\n")

        # ── IRB summary ────────────────────────────────────────────────────
        if d["irb"]["count"] > 0:
            buf.write(
                f"<h2>Research Protocols (IRB)</h2>\n"
                f"<table><tr><th>Metric</th><th>Value</th></tr>\n"
                f"<tr><td>Total protocols registered</td>"
                f"<td>{d['irb']['count']}</td></tr>\n"
                f"<tr><td>Currently active protocols</td>"
                f"<td>{d['irb']['active']}</td></tr>\n"
            )
            if self.show_irb_titles and d["irb"]["titles"]:
                for title in d["irb"]["titles"]:
                    buf.write(
                        f"<tr><td>Study</td><td>{_he(title)}</td></tr>\n"
                    )
            buf.write("</table>\n")

        # ── Vendor summary ─────────────────────────────────────────────────
        if self.include_vendors and d["vendors"]["count"] > 0:
            buf.write(
                f"<h2>Vendor Management</h2>\n"
                f"<table><tr><th>Metric</th><th>Value</th></tr>\n"
                f"<tr><td>Total vendors reviewed</td>"
                f"<td>{d['vendors']['count']}</td></tr>\n"
                f"<tr><td>SOC 2 certified vendors</td>"
                f"<td>{d['vendors']['soc2_certified']}</td></tr>\n"
                f"<tr><td>Data Processing Agreements signed</td>"
                f"<td>{d['vendors']['dpa_signed']}</td></tr>\n"
                f"</table>\n"
            )

        # ── Consent summary ────────────────────────────────────────────────
        if d["consent"]["total_records"] > 0:
            purposes_str = ", ".join(d["consent"]["purposes"]) or "—"
            buf.write(
                f"<h2>Consent Management</h2>\n"
                f"<table><tr><th>Metric</th><th>Value</th></tr>\n"
                f"<tr><td>Total consent records</td>"
                f"<td>{d['consent']['total_records']:,}</td></tr>\n"
                f"<tr><td>Processing purposes covered</td>"
                f"<td>{_he(purposes_str)}</td></tr>\n"
                f"</table>\n"
            )

        # ── Live controls check ────────────────────────────────────────────
        ctrl_data = d.get("controls", {})
        if ctrl_data.get("available") and ctrl_data.get("results"):
            results  = ctrl_data["results"]
            passed   = sum(1 for r in results if r["status"] == "OK")
            buf.write(
                f"<h2>Controls Monitoring</h2>\n"
                f"<p>{passed} of {len(results)} controls passing "
                f"(last checked: {_he(results[0].get('checked_at','')[:19])} UTC)</p>\n"
                f"<table><tr><th>Control</th><th>Status</th><th>Detail</th></tr>\n"
            )
            for r in results:
                badge = {"OK": "badge-green", "WARN": "badge-yellow",
                         "FAIL": "badge-red"}.get(r["status"], "badge-blue")
                buf.write(
                    f"<tr><td><code>{_he(r['control_id'])}</code></td>"
                    f"<td><span class='badge {badge}'>{_he(r['status'])}</span></td>"
                    f"<td>{_he(r['detail'])}</td></tr>\n"
                )
            buf.write("</table>\n")

        buf.write(_html_foot())
        return buf.getvalue()


# ═════════════════════════════════════════════════════════════════════════════
#  Exceptions
# ═════════════════════════════════════════════════════════════════════════════

class ComplianceControlFailedError(Exception):
    """
    Raised when a ComplianceMonitor check fails and the caller has opted
    to treat failures as hard errors.
    """
